//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadedDropDown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public int state_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string state { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
